# Baza danych
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/portfolio_tracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:120412}
spring.datasource.url=jdbc:postgresql://zephyr.proxy.rlwy.net:43387/railway
spring.datasource.username=postgres
spring.datasource.password=HXxuyGOhzqQKqyFHqbXkVZydMNAQLzEe
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# API keys
finnhub.api.key=${FINNHUB_API_KEY:d89v2o1r01qhi7ru50egd89v2o1r01qhi7ru50f0}

# Scheduler co 15 minut
news.refresh.rate=900000

# Scheduling enabled
spring.task.scheduling.enabled=true